# Generated by Django 5.0.14 on 2025-11-27 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voto',
            name='candidato',
        ),
        migrations.AddField(
            model_name='candidato',
            name='cargo',
            field=models.CharField(choices=[('rector', 'Rector'), ('vicerrector', 'Vicerrector')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voto',
            name='rector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votos_rector', to='usuarios.candidato'),
        ),
        migrations.AddField(
            model_name='voto',
            name='vicerrector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votos_vicerrector', to='usuarios.candidato'),
        ),
    ]
