# Generated by Django 5.0.14 on 2025-11-27 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_voto_candidato_candidato_cargo_voto_rector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voto',
            name='rector',
            field=models.ForeignKey(blank=True, limit_choices_to={'cargo': 'rector'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votos_rector', to='usuarios.candidato'),
        ),
        migrations.AlterField(
            model_name='voto',
            name='vicerrector',
            field=models.ForeignKey(blank=True, limit_choices_to={'cargo': 'vicerrector'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votos_vicerrector', to='usuarios.candidato'),
        ),
    ]
